# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1800a120b06f8aa405d03593d81972b8ef767f630f6df2b4c79f4a7bc67555b35baa0fc12713d4fce1806983e7db3a5074e6e8a0d6a9c200a0215d1f1b34ca

test:
  secret_key_base: cb201e804e7cf5199e83926d16fd82fe595afefb5fe09b99734b92888b22d6e95a62115fdd263cf746b18a7a65f737eed0256471064c15311bd3174afc497fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
